[cerebrium.deployment]
name = "neon-essence-agents"
python_version = "3.11"
docker_base_image_url = "debian:bookworm-slim"
include = [
    "avatar_worker.py",
    "main.py",
    "requirements.txt",
    "Dockerfile",
]
exclude = [".*"]

[cerebrium.hardware]
cpu = 4
memory = 6.0

[cerebrium.scaling]
min_replicas = 1               # Minimum running instances
max_replicas = 100             # Maximum concurrent instances
cooldown = 5                   # Cooldown period in seconds
replica_concurrency = 2        # The maximum number of requests each replica of an app can accept
response_grace_period = 43200  # Maximum request lifespan ensuring graceful exit
scaling_target = 100
scaling_metric = "concurrency_utilization"
