[cerebrium.deployment]
name = "cpu-avatar-service"
include = [
    "Dockerfile",
    "avatar_worker.py",
    "dispatcher.py",
    "agent_message_handler.py",
    "avatar_actions.py",
    "requirements.txt",
]


[cerebrium.hardware]
cpu = 6
memory = 8.0

[cerebrium.scaling]
min_replicas = 1               # Minimum running instances
max_replicas = 100             # Maximum concurrent instances
cooldown = 10                  # Cooldown period in seconds
replica_concurrency = 1        # The maximum number of requests each replica of an app can accept
response_grace_period = 43200  # Maximum request lifespan ensuring graceful exit
scaling_target = 100
scaling_metric = "concurrency_utilization"

[cerebrium.runtime.custom]
port = 8089
healthcheck_endpoint = "/health"
readycheck_endpoint = "/ready"
dockerfile_path = "./Dockerfile"